name: Header Confirmation

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  header-confirm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install python-frontmatter
      - name: Confirm headers
        run: python optunahub-registry/header_confirm.py
