name: Test OptunaHub Web Build
on:
  push:
    branches:
      - main
  pull_request: {}

permissions:
  contents: read

jobs:
  test-optunahub-web-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'
      - name: Clone optunahub-web
        run: git clone https://github.com/optuna/optunahub-web.git
      - name: Create optuna-registry under optunahub-web
        run: mkdir optunahub-web/optunahub-registry
      - name: Clone optuna-registry under optunahub-web
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: optunahub-web/optunahub-registry
      - name: Install dependencies of optunahub-web
        working-directory: ./optunahub-web
        run: pip install -r requirements.txt
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
        with:
          hugo-version: '0.124.1'
      - name: Build optunahub-web
        working-directory: ./optunahub-web
        run: make build
      - name: Clean up
        run: rm -rf optunahub-web
